### ISSUE TITLE
How to delete an image?

### ISSUE THREAD

**Issue by Happ1ness-dev** [carefree0910/carefree-creator#1]
I've generated a bunch of images, but I've got a problem, idk how to delete them.

There's no delete option, I've tried everything.
Maybe it's because I'm using phone ¯⁠\⁠_⁠(⁠ツ⁠)⁠_⁠/⁠¯

**Comment by carefree0910** [comment]
Oh, that's indeed why you cannot delete an image 🤣 Because I currently bind the 'Delete' shortcut on **keyboard** to the image deletion.

I'm going to optimize the behaviors on phones in the near future, I'll come back to notify you once I'm satisfied with it 😉

But for now, let's try it on computers, it should have much better user experience 😆

**Comment by Happ1ness-dev** [comment]
> Oh, that's indeed why you cannot delete an image 🤣 Because I currently bind the 'Delete' shortcut on **keyboard** to the image deletion.
> 
> I'm going to optimize the behaviors on phones in the near future, I'll come back to notify you once I'm satisfied with it 😉
> 
> But for now, let's try it on computers, it should have much better user experience 😆


Ok, but I don't have a PC, so I'll just wait :)

**Comment by Happ1ness-dev** [comment]
Rn I'm just using undo to delete the images, as a workaround

**Comment by carefree0910** [comment]
That's smart I missed that 🤣.

**Comment by carefree0910** [comment]
In case you are still interested, now it has a `Delete` button on the right after you select an image! 😉

**Comment by Happ1ness-dev** [comment]
Noice :)
